name: Pull request

on:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  pull-request:
    name: Pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # ratchet:actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'
      - name: Test and build
        env:
          GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify

